# Generated by Django 3.2 on 2021-05-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Autor')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Titulo')),
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de Publicación')),
                ('fecha_modificacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.autor')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
